
## Git shortcut
alias ga='git add'
alias gps='git push'
alias gpus='git push'
alias gpush='git push'
alias gl='git log'
alias gs='git status'
alias gd='git diff'
alias gc='git commit'
alias gm='git commit -m'
alias gma='git commit -am'
alias gb='git branch'
alias gck='git checkout'
alias gra='git remote add'
alias grr='git remote rm'
alias gpu='git pull'
alias gcl='git clone'
alias gst='git stash'
alias gpo='git stash pop'

## Divers
alias ll='ls -la'
alias cc='clear'
alias va='vagrant'
